- module-name: 'UnityPy'
  data-files:
    patterns:
      - 'resources/uncompressed.tpk'

- module-name: 'fmod_toolkit'
  data-files:
    patterns:
      - 'libfmod/Windows/**/*.dll' 
      - 'libfmod/Linux/**/*.so'
      - 'libfmod/Darwin/*.dylib'

- module-name: 'archspec'
  data-files:

    patterns:
      - 'json/cpu/cpuid.json'
      - 'json/cpu/cpuid_schema.json'
      - 'json/cpu/microarchitectures.json'
      - 'json/cpu/microarchitectures_schema.json'
      - 'json/cpu/*.json'
